export const BRAZILIAN_BANKS = [
  'BANCO DO BRASIL S.A.', 'BANCO BRADESCO S.A.', 'ITAÚ UNIBANCO S.A.', 'CAIXA ECONOMICA FEDERAL', 'BANCO SANTANDER (BRASIL) S.A.',
  'BANCO BTG PACTUAL S.A.', 'BANCO SAFRA S.A.', 'BANCO PAN S.A.', 'BANCO INTER S.A.', 'BANCO C6 S.A.',
  'BANCO MERCANTIL DO BRASIL S.A.', 'BANCO ORIGINAL S.A.', 'BANCO MODAL S.A.', 'BANCO NEON S.A.', 'BANCO BMG S.A.',
  'BANCO XP S.A.', 'BANCO SICOOB S.A.', 'BANCO SICREDI S.A.', 'BANCO DAYCOVAL S.A.', 'BANCO SOFISA S.A.',
  'PICPAY SERVICOS S.A.', 'STONE PAGAMENTOS S.A.', 'MERCADO PAGO INSTITUICAO DE PAGAMENTO LTDA',
  'BANCO RENDIMENTO S.A.', 'BANCO ABC BRASIL S.A.', 'BANCO CREFISA S.A.', 'BANCO FIBRA S.A.',
  'NU PAGAMENTOS - IP'
];

export const NOTIF_SOUND = '/som.mp3';

export const CONFIRMACOES = [
  "sim, sou eu!",
  "isso simm!!",
  "simmmmm",
  "opaaa sou eu sim",
  "sim, participei sim!",
  "sim, eu mesmo!",
  "simm, fui eu",
  "sim sim, sou eu",
  "issoo, eu!!",
  "sim, claro!!",
  "siim, eu tava la",
  "com certeza",
  "sou eu sim!",
  "sim, pode crer",
  "simmmm, eu!",
  "isso, sou eu",
  "sim, tava na live",
  "simm!",
  "sim, opa sou eu",
  "sim sim sim!",
  "claro, sou eu",
  "simm, isso ai",
  "sim, participei",
  "isso memo sou eu",
  "opa, sim sou eu",
  "isso ai, eu!",
  "com certeza sou eu",
  "sim, tava sim",
  "sim, valeu",
  "sim, eu mesmo!",
];

export const RESPOSTAS_30 = [
  "vlw mesmo","obrigado","chegou sim","valeu","brigadão",
  "só gratidão","obrigadão","Deus te abençoe","valeu demais",
  "só sucesso","pode crer","tmj","obrigado de coração",
  "paz e bençãos","Deus te pague","muito obrigado",
  "agradeço demais","top demais","só sucesso chegou sim",
  "valeu de boa","que isso fera","obrigado demais",
  "n esperava por essa","vlw de boa","que isso mano",
  "ce é brabo demais","parceiro vc é fera",
];

export const RESPOSTAS_80 = [
  "nunca duvidei","obrigado de coração mesmo",
  "não esperava nada assim, valeu demais",
  "salvou minha semana patrão infinitos obgd ai",
  "obrigado demais, isso vai ajudar muito",
  "cara ce salvou meu dia",
  "to sem palavras, obg",
  "manda bem demais vei",
  "era oq tava precisando cara ....... caralho!",
  "n acredito que caiu na conta",
  "pode parar de ser bom demais kkk",
  "vlw mesmo, tava no sufoco",
  "obrigado mano isso muda tudo aqui em casa",
  "Deus te pague tudo mano",
  "caralho real msm? valeu!",
  "que tipo de anjo é vc",
  "obrigadão, paga meu lanche da semana",
  "só gratidão mesmo",
  "voce nao imagina o quanto eu tava precisando agora",
  "salvou minha família essa semana",
  "nunca vi isso, achei que era brincadeira",
  "obrigado demais, vai dar pra pagar aquela conta",
];

export const RESPOSTAS_150 = [
  "meu deus mano é serio isso? salvou demais achei que tava brincando",
  "putz mano voce salvou minha vida",
  "esse valor vai fazer diferença pra mim cara muito obg",
  "cego de pedra aqui tu mandou mesmo piá KAKAKAKA",
  "cara eu tava prestes a ser despejado eu nao to nem acreditando q tu mandou mesmo vou poder quitar os atrasado amanha",
  "obrigado mano isso muda tudo aqui em casa",
  "to tremendo, caiu de verdade",
  "vc é diferenciado mesmo, Deus te abençoe",
  "isso aqui paga minhas contas do mês",
  "caramba, tu é brabo",
  "to chorando mano, obrigado",
  "pode crer que vício em bondade",
  "Deus te pague infinito",
  "mano ce é fora do normal",
  "obrigado de coração mesmo",
  "nunca pensei que ia receber isso",
  "tu é luz na minha vida",
  "não esperava nada assim, valeu demais",
  "esse valor vai mudar minha vida, obrigado de verdade",
  "Deus te abençoe grandemente, salvou minha família",
];